export { MinimaxError } from './src/errors'
export type { MinimaxErrorCode } from './src/errors'
export { minimaxFetch } from './src/client'
export { generateImage } from './src/image'
export type { GenerateImageOptions, GenerateImageResult } from './src/image'
export { generateText } from './src/text'
export type { GenerateTextOptions, GenerateTextResult } from './src/text'
export { generateMusic } from './src/music'
export type { GenerateMusicOptions, GenerateMusicResult } from './src/music'
export { generateLyrics } from './src/lyrics'
export type { GenerateLyricsOptions, GenerateLyricsResult } from './src/lyrics'
